spring:
  application:
    name: basic-service
  servlet:
    multipart:
      max-request-size: 120MB
      max-file-size: 120MB
  redis:
    host: 139.196.86.188
    password: AdeTTT32312ttedsdcaHUHU
    port: 3333
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/basic?useUnicode=true&amp;characterEncoding=UTF-8
    password: basic
    username: basic
    driver-class-name: org.postgresql.Driver
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  page:
    abc: just
server:
  port: 8081
  servlet:
    context-path: /basic
dubbo:
  port: 20001
  basic:
    version: 1.0
kafka:
  topic: basic-service
