CREATE TABLE T_COUNTRY_3166
(
  ID        	 	        			VARCHAR(64) NOT NULL PRIMARY KEY,
  FIFA              					VARCHAR(64),
  DIAL              					VARCHAR(64),
  ALPHA_CODE_3              			VARCHAR(64),
  MARC                 					VARCHAR(64),
  IS_INDEPENDENT            			VARCHAR(256),
  NUMBER_CODE               			VARCHAR(64),
  GAUL               					VARCHAR(64),
  FIPS                   				VARCHAR(64),
  WMO          							VARCHAR(64),
  ALPHA_CODE_2              			VARCHAR(64),
  ITU            						VARCHAR(64),
  IOC                    				VARCHAR(64),
  DS                					VARCHAR(64),
  GLOBAL_CODE							VARCHAR(32),
  INTERMEDIATE_REGION_CODE				VARCHAR(64),
  DEVELOP_TYPE							VARCHAR(64),
  UNIVERSAL_CURRENCY					VARCHAR(256),
  SMALL_ISLAND_DEVELOPING_STATUS		VARCHAR(256),
  M49									VARCHAR(64),
  SUB_REGION_CODE						VARCHAR(64),
  REGION_CODE							VARCHAR(64),
  LAND_LOCKED_DEVELOPING_COUNTRIES		VARCHAR(64),
  INTERMEDIATE_REGION_NAME				VARCHAR(256),
  OFFICIAL_NAME_CN						VARCHAR(1024),
  OFFICIAL_NAME_EN						VARCHAR(1024),
  ISO_3166_NAME							VARCHAR(1024),
  LOCALE_NAME							VARCHAR(1024),
  LASTED_DEVELOPED_COUNTRIES			VARCHAR(256),
  REGION_NAME							VARCHAR(256),
  SUB_REGION_NAME						VARCHAR(256),
  GLOBAL_NAME							VARCHAR(64),
  CAPITAL								VARCHAR(256),
  CONTINENT								VARCHAR(64),
  TLD									VARCHAR(64),
  LANGUAGES								VARCHAR(256),
  GEONAME_ID							VARCHAR(36),
  CLDR_DISPLAY_NAME						VARCHAR(1024),
  EDGAR									VARCHAR(64),
  STATUS                    			VARCHAR(64),
  UPDATE_USER_ID            			VARCHAR(64),
  CREATE_USER_ID          				VARCHAR(64),
  EXPIRE_DATETIME						TIMESTAMP WITHOUT TIME ZONE,
  UPDATE_DATETIME         				TIMESTAMP WITHOUT TIME ZONE,
  CREATE_DATETIME         				TIMESTAMP WITHOUT TIME ZONE
);

CREATE SEQUENCE SEQ_COUNTRY_3166 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;

COMMENT ON TABLE  T_COUNTRY_3166 					                  			IS '国家表';
COMMENT ON COLUMN T_COUNTRY_3166.ID 				                  			IS '主键';
COMMENT ON COLUMN T_COUNTRY_3166.FIFA 				                  			IS '国际足球联盟';
COMMENT ON COLUMN T_COUNTRY_3166.DIAL 				                  			IS '国际电话前缀';
COMMENT ON COLUMN T_COUNTRY_3166.ALPHA_CODE_3 				                  	IS '3166 3字码';
COMMENT ON COLUMN T_COUNTRY_3166.MARC 				                  			IS '机读目录';
COMMENT ON COLUMN T_COUNTRY_3166.IS_INDEPENDENT 				                IS '是否独立国家';
COMMENT ON COLUMN T_COUNTRY_3166.NUMBER_CODE 				                  	IS '3166 数字码';
COMMENT ON COLUMN T_COUNTRY_3166.GAUL 				                  			IS '不知道是什么缩写';
COMMENT ON COLUMN T_COUNTRY_3166.FIPS 				                  			IS '联邦信息处理标准';
COMMENT ON COLUMN T_COUNTRY_3166.WMO 				                  			IS '世界气象组织';
COMMENT ON COLUMN T_COUNTRY_3166.ALPHA_CODE_2 				                  	IS '3166 2字码';
COMMENT ON COLUMN T_COUNTRY_3166.ITU 				                  			IS '国际电信联盟标准';
COMMENT ON COLUMN T_COUNTRY_3166.IOC 				                  			IS '国际奥林匹克标准';
COMMENT ON COLUMN T_COUNTRY_3166.DS 				                  			IS '不知道是什么标准';
COMMENT ON COLUMN T_COUNTRY_3166.GLOBAL_CODE 				                  	IS '国际CODE';
COMMENT ON COLUMN T_COUNTRY_3166.INTERMEDIATE_REGION_CODE 				        IS '中间地区编码';
COMMENT ON COLUMN T_COUNTRY_3166.DEVELOP_TYPE 				                  	IS '发展类型';
COMMENT ON COLUMN T_COUNTRY_3166.UNIVERSAL_CURRENCY 				            IS '通用币种使用,分割';
COMMENT ON COLUMN T_COUNTRY_3166.SMALL_ISLAND_DEVELOPING_STATUS 				IS '是否是发展的小岛???';
COMMENT ON COLUMN T_COUNTRY_3166.M49 				                  			IS '不知道是什么缩写';
COMMENT ON COLUMN T_COUNTRY_3166.SUB_REGION_CODE 				                IS '子地区编码';
COMMENT ON COLUMN T_COUNTRY_3166.REGION_CODE 				                  	IS '地区编码';
COMMENT ON COLUMN T_COUNTRY_3166.LAND_LOCKED_DEVELOPING_COUNTRIES 				IS '地区编码';
COMMENT ON COLUMN T_COUNTRY_3166.INTERMEDIATE_REGION_NAME 				        IS '地区编码';
COMMENT ON COLUMN T_COUNTRY_3166.OFFICIAL_NAME_EN 				                IS '英文正式名字';
COMMENT ON COLUMN T_COUNTRY_3166.OFFICIAL_NAME_CN 				                IS '中文正式名字';
COMMENT ON COLUMN T_COUNTRY_3166.ISO_3166_NAME 				                	IS '3166国家名称';
COMMENT ON COLUMN T_COUNTRY_3166.LOCALE_NAME 				                  	IS '本地化名称';
COMMENT ON COLUMN T_COUNTRY_3166.LASTED_DEVELOPED_COUNTRIES 				    IS '是否最后的发展国家???';
COMMENT ON COLUMN T_COUNTRY_3166.REGION_NAME 				                  	IS '地区名称';
COMMENT ON COLUMN T_COUNTRY_3166.SUB_REGION_NAME 				                IS '子地区名称';
COMMENT ON COLUMN T_COUNTRY_3166.GLOBAL_NAME 				                  	IS '全球名称';
COMMENT ON COLUMN T_COUNTRY_3166.CAPITAL 				                  		IS '首都';
COMMENT ON COLUMN T_COUNTRY_3166.CONTINENT 				                  		IS '国家';
COMMENT ON COLUMN T_COUNTRY_3166.TLD 				                  			IS '顶级域名';
COMMENT ON COLUMN T_COUNTRY_3166.LANGUAGES 				                  		IS '通用的语言使用,分割';
COMMENT ON COLUMN T_COUNTRY_3166.GEONAME_ID 				                  	IS '地理位置ID';
COMMENT ON COLUMN T_COUNTRY_3166.CLDR_DISPLAY_NAME 				                IS '不知道什么显示名称';
COMMENT ON COLUMN T_COUNTRY_3166.EDGAR 				                			IS '检索系统';
COMMENT ON COLUMN T_COUNTRY_3166.STATUS 				                  		IS '状态';
COMMENT ON COLUMN T_COUNTRY_3166.UPDATE_USER_ID 				                IS '更新操作员';
COMMENT ON COLUMN T_COUNTRY_3166.CREATE_USER_ID 				                IS '创建操作员';
COMMENT ON COLUMN T_COUNTRY_3166.EXPIRE_DATETIME 				                IS '过期时间';
COMMENT ON COLUMN T_COUNTRY_3166.UPDATE_DATETIME 				                IS '更新时间';
COMMENT ON COLUMN T_COUNTRY_3166.CREATE_DATETIME 				                IS '创建时间';

CREATE TABLE T_APP_DEF
(
	ID								VARCHAR(64) NOT NULL PRIMARY KEY,
	APP_NAME						VARCHAR(256) NOT NULL,
	GROUP_NAME						VARCHAR(256),
	OWN_USER_ID						VARCHAR(64),
	SERVER_PORT						SMALLINT NOT NULL,
	DUBBO_PORT						INT,
	KAFKA_TOPIC						VARCHAR(256),
	EXT_SETTING						VARCHAR(256),
	EXT1_SETTING					VARCHAR(256),
	CONTEXT_PATH					VARCHAR(64),
	APP_DESC						VARCHAR(1024),
	STATUS							VARCHAR(64),
	UPDATE_USER_ID    				VARCHAR(64),
	CREATE_USER_ID    				VARCHAR(64),
	EXPIRE_DATETIME					TIMESTAMP WITHOUT TIME ZONE,
	UPDATE_DATETIME   				TIMESTAMP WITHOUT TIME ZONE,
	CREATE_DATETIME   				TIMESTAMP WITHOUT TIME ZONE
);

CREATE UNIQUE INDEX I_APP_NAME ON T_APP_DEF (APP_NAME);

CREATE SEQUENCE SEQ_APP_DEF INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;

COMMENT ON TABLE  T_APP_DEF 					        IS '服务表';
COMMENT ON COLUMN T_APP_DEF.ID 				        	IS '主键';
COMMENT ON COLUMN T_APP_DEF.APP_NAME 			    	IS '服务名';
COMMENT ON COLUMN T_APP_DEF.GROUP_NAME 			  		IS '服务分组名';
COMMENT ON COLUMN T_APP_DEF.OWN_USER_ID 				IS '服务OWNER用户';
COMMENT ON COLUMN T_APP_DEF.SERVER_PORT 				IS '服务端口';
COMMENT ON COLUMN T_APP_DEF.DUBBO_PORT 			  		IS 'DUBBO端口';
COMMENT ON COLUMN T_APP_DEF.KAFKA_TOPIC 				IS 'KAFKA话题,通常用于任务下发';
COMMENT ON COLUMN T_APP_DEF.EXT_SETTING 				IS '额外设置';
COMMENT ON COLUMN T_APP_DEF.EXT1_SETTING 				IS '额外设置1';
COMMENT ON COLUMN T_APP_DEF.CONTEXT_PATH 				IS '服务前缀';
COMMENT ON COLUMN T_APP_DEF.APP_DESC 			    	IS '服务描述';
COMMENT ON COLUMN T_APP_DEF.STATUS 		        		IS '是否可用';
COMMENT ON COLUMN T_APP_DEF.UPDATE_USER_ID 	  			IS '更新操作员';
COMMENT ON COLUMN T_APP_DEF.CREATE_USER_ID 	  			IS '创建操作员';
COMMENT ON COLUMN T_APP_DEF.EXPIRE_DATETIME 			IS '过期时间';
COMMENT ON COLUMN T_APP_DEF.UPDATE_DATETIME 			IS '更新时间';
COMMENT ON COLUMN T_APP_DEF.CREATE_DATETIME 			IS '创建时间';


CREATE TABLE T_CACHE_DEF
(
	ID								VARCHAR(64) NOT NULL PRIMARY KEY,
	CACHE_NAME						VARCHAR(256) NOT NULL,
	APP_NAME						VARCHAR(256),
	CACHE_ZK_PATH					VARCHAR(512),
	CACHE_REDIS_KEY					VARCHAR(512),
	CACHE_INS_CLASS					VARCHAR(1024),
	BRIDGE_CLASS					VARCHAR(1024),
	CARRIER_CLASS					VARCHAR(1024),
	IS_GLOBAL						VARCHAR(64),
	IS_DURABLE						VARCHAR(64),
	DURATION_OF_MINUTES				INT,
	LAST_LOAD_DATETIME				TIMESTAMP WITHOUT TIME ZONE,
	STATUS							VARCHAR(64),
	UPDATE_USER_ID					VARCHAR(64),
	CREATE_USER_ID					VARCHAR(64),
	EXPIRE_DATETIME       			TIMESTAMP WITHOUT TIME ZONE,
	UPDATE_DATETIME       			TIMESTAMP WITHOUT TIME ZONE,
	CREATE_DATETIME       			TIMESTAMP WITHOUT TIME ZONE
);

CREATE UNIQUE INDEX I_CACHE_APP_NAME ON T_CACHE_DEF (CACHE_NAME,APP_NAME);

CREATE UNIQUE INDEX I_CACHE_ZK_PATH ON T_CACHE_DEF (CACHE_ZK_PATH);

CREATE UNIQUE INDEX I_CACHE_REDIS_KEY ON T_CACHE_DEF (CACHE_REDIS_KEY);

CREATE SEQUENCE SEQ_CACHE_DEF INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;

COMMENT ON TABLE  T_CACHE_DEF										IS '缓存表';
COMMENT ON COLUMN T_CACHE_DEF.ID									IS '主键';
COMMENT ON COLUMN T_CACHE_DEF.CACHE_NAME 			        		IS '缓存名';
COMMENT ON COLUMN T_CACHE_DEF.APP_NAME 			          			IS '所在服务名';
COMMENT ON COLUMN T_CACHE_DEF.CACHE_ZK_PATH 			    		IS '缓存在的ZOOKEEPER PATH 用于更新全局缓存,比如说国家之类的通知监听地址,不是全局可置为空';
COMMENT ON COLUMN T_CACHE_DEF.CACHE_REDIS_KEY 			  			IS '缓存在的REDIS_KEY';
COMMENT ON COLUMN T_CACHE_DEF.CACHE_INS_CLASS 			  			IS '缓存的CLASS类名';
COMMENT ON COLUMN T_CACHE_DEF.BRIDGE_CLASS 			     			IS '缓存的BRIDGE类名';
COMMENT ON COLUMN T_CACHE_DEF.CARRIER_CLASS 			    		IS 'CARRIER类';
COMMENT ON COLUMN T_CACHE_DEF.IS_GLOBAL 			        		IS '是否全局缓存 true/false';
COMMENT ON COLUMN T_CACHE_DEF.IS_DURABLE 			        		IS '是否长期缓存 true/false';
COMMENT ON COLUMN T_CACHE_DEF.DURATION_OF_MINUTES 					IS '过期分钟';
COMMENT ON COLUMN T_CACHE_DEF.LAST_LOAD_DATETIME 					IS '最后一次更新时间';
COMMENT ON COLUMN T_CACHE_DEF.STATUS 		              			IS '是否可用';
COMMENT ON COLUMN T_CACHE_DEF.UPDATE_USER_ID 	        			IS '更新操作员';
COMMENT ON COLUMN T_CACHE_DEF.CREATE_USER_ID 	        			IS '创建操作员';
COMMENT ON COLUMN T_CACHE_DEF.EXPIRE_DATETIME 	      				IS '过期时间';
COMMENT ON COLUMN T_CACHE_DEF.UPDATE_DATETIME 	      				IS '更新时间';
COMMENT ON COLUMN T_CACHE_DEF.CREATE_DATETIME 	     				IS '创建时间';

CREATE TABLE T_BIZ_TABLE_DEF
(
	ID								VARCHAR(64) NOT NULL PRIMARY KEY,
	TABLE_NAME 						VARCHAR(256) NOT NULL,
	SCHEMA_NAME				    	VARCHAR(256),
	APP_NAME          				VARCHAR(256),
	T_CLASS 				  		VARCHAR(1024) NOT NULL,
	PATTERN           				VARCHAR(64),
	BIZ_CODE          				SMALLINT NOT NULL,
	PREFIX 					  		VARCHAR(4),
	THE_DESC 						VARCHAR(1024),
	IS_SYS					  		VARCHAR(64),
	STATUS          				VARCHAR(64),
	UPDATE_USER_ID    				VARCHAR(64),
	CREATE_USER_ID    				VARCHAR(64),
	CREATE_DATETIME   				TIMESTAMP WITHOUT TIME ZONE
);

CREATE UNIQUE INDEX I_TABLE_NAME_SCHEMA ON T_BIZ_TABLE_DEF (TABLE_NAME,SCHEMA_NAME);

CREATE SEQUENCE SEQ_BIZ_TABLE_CONF INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;

COMMENT ON TABLE  T_BIZ_TABLE_DEF									IS '业务表配置';
COMMENT ON COLUMN T_BIZ_TABLE_DEF.ID 				        		IS '主键';
COMMENT ON COLUMN T_BIZ_TABLE_DEF.TABLE_NAME 			  			IS '表名';
COMMENT ON COLUMN T_BIZ_TABLE_DEF.SCHEMA_NAME 			      		IS '库名';
COMMENT ON COLUMN T_BIZ_TABLE_DEF.APP_NAME 			    			IS '服务名';
COMMENT ON COLUMN T_BIZ_TABLE_DEF.T_CLASS 			    			IS '类全名';
COMMENT ON COLUMN T_BIZ_TABLE_DEF.PATTERN 				  			IS '分表模式 YYYY_MM, YYYY_MM_DD';
COMMENT ON COLUMN T_BIZ_TABLE_DEF.BIZ_CODE 			    			IS '业务CODE(0-31)';
COMMENT ON COLUMN T_BIZ_TABLE_DEF.PREFIX 				    		IS 'ID前缀';
COMMENT ON COLUMN T_BIZ_TABLE_DEF.THE_DESC 			    			IS '业务分表描述';
COMMENT ON COLUMN T_BIZ_TABLE_DEF.IS_SYS 		        			IS '是否系统';
COMMENT ON COLUMN T_BIZ_TABLE_DEF.STATUS 		        			IS '是否可用';
COMMENT ON COLUMN T_BIZ_TABLE_DEF.UPDATE_USER_ID 	  				IS '更新操作员';
COMMENT ON COLUMN T_BIZ_TABLE_DEF.CREATE_USER_ID  					IS '创建操作员';
COMMENT ON COLUMN T_BIZ_TABLE_DEF.CREATE_DATETIME 					IS '创建时间';

CREATE TABLE T_CURRENCY_4217
(
  ID        	 	     			VARCHAR(64) NOT NULL PRIMARY KEY,
  ALPHA_CODE						VARCHAR(6) ,
  NUMBER_CODE						VARCHAR(6) ,
  MINOR_UNIT						SMALLINT DEFAULT 0,
  SYMBOL_CURRENCY					VARCHAR(6),
  I18N_KEY							VARCHAR(32),
  OFFICIAL_NAME_EN                	VARCHAR(128),
  OFFICIAL_NAME_CN         			VARCHAR(256),
  LOCALE_NAME             			VARCHAR(256),
  GRANT_4_SALE        				VARCHAR(64),
  GRANT_4_SETTLE      				VARCHAR(64),
  STATUS              				VARCHAR(64),
  UPDATE_USER_ID      				VARCHAR(64),
  CREATE_USER_ID      				VARCHAR(64),
  EXPIRE_DATETIME     				TIMESTAMP WITHOUT TIME ZONE,
  UPDATE_DATETIME     				TIMESTAMP WITHOUT TIME ZONE,
  CREATE_DATETIME     				TIMESTAMP WITHOUT TIME ZONE
);

CREATE SEQUENCE SEQ_CURRENCY_4217 INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;

COMMENT ON TABLE  T_CURRENCY_4217 					                IS '币种表';
COMMENT ON COLUMN T_CURRENCY_4217.ID 				                IS '主键';
COMMENT ON COLUMN T_CURRENCY_4217.ALPHA_CODE 			          	IS '币种字母码';
COMMENT ON COLUMN T_CURRENCY_4217.NUMBER_CODE 			        	IS '币种数字码';
COMMENT ON COLUMN T_CURRENCY_4217.MINOR_UNIT 			          	IS '币种最小单位';
COMMENT ON COLUMN T_CURRENCY_4217.SYMBOL_CURRENCY 			    	IS '币种符号';
COMMENT ON COLUMN T_CURRENCY_4217.I18N_KEY 				          	IS '币种I18N';
COMMENT ON COLUMN T_CURRENCY_4217.OFFICIAL_NAME_EN 			        IS '币种英文名';
COMMENT ON COLUMN T_CURRENCY_4217.OFFICIAL_NAME_CN 			        IS '币种中文名';
COMMENT ON COLUMN T_CURRENCY_4217.LOCALE_NAME 			            IS '币种当地名';
COMMENT ON COLUMN T_CURRENCY_4217.GRANT_4_SALE 				      	IS '是否是交易币种true/false';
COMMENT ON COLUMN T_CURRENCY_4217.GRANT_4_SETTLE 			      	IS '是否是结算币种true/false';
COMMENT ON COLUMN T_CURRENCY_4217.STATUS 		                	IS '是否可用';
COMMENT ON COLUMN T_CURRENCY_4217.UPDATE_USER_ID 	          		IS '更新操作员';
COMMENT ON COLUMN T_CURRENCY_4217.CREATE_USER_ID 	          		IS '创建操作员';
COMMENT ON COLUMN T_CURRENCY_4217.EXPIRE_DATETIME 	        		IS '过期时间';
COMMENT ON COLUMN T_CURRENCY_4217.UPDATE_DATETIME 	        		IS '更新时间';
COMMENT ON COLUMN T_CURRENCY_4217.CREATE_DATETIME 	        		IS '创建时间';

CREATE TABLE T_DICT_DATA
(
	DICT_CODE                 		VARCHAR(64) NOT NULL  PRIMARY KEY,
	PARENT_CODE               		VARCHAR(64) NOT NULL,
	TREE_SORT                 		SMALLINT NOT NULL,
	TREE_LEAF                 		VARCHAR(64) NOT NULL,
	TREE_LEVEL                		SMALLINT NOT NULL,
	DICT_LABEL                		VARCHAR(128) NOT NULL,
	DICT_VALUE                		VARCHAR(128) NOT NULL,
	DICT_NAME                 		VARCHAR(128) NOT NULL,
	DICT_TAG                  		VARCHAR(256) NOT NULL,
	IS_SYS                    		VARCHAR(64) NOT NULL,
	IS_DEFAULT                		VARCHAR(64) NOT NULL,
	THE_DESC                  		VARCHAR(1024),
	STATUS                    		VARCHAR(64),
	UPDATE_USER_ID            		VARCHAR(64),
	CREATE_USER_ID            		VARCHAR(64),
	EXPIRE_DATETIME					TIMESTAMP WITHOUT TIME ZONE,
	UPDATE_DATETIME           		TIMESTAMP WITHOUT TIME ZONE,
	CREATE_DATETIME           		TIMESTAMP WITHOUT TIME ZONE
);

CREATE SEQUENCE SEQ_DICT_DATA INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;
CREATE INDEX I_PARENT_CODE ON T_DICT_DATA (PARENT_CODE);
CREATE INDEX I_DATA_DICT_NAME ON T_DICT_DATA (DICT_NAME);

COMMENT ON TABLE  T_DICT_DATA 					                	IS '字典数据表';
COMMENT ON COLUMN T_DICT_DATA.DICT_CODE 				        	IS '字典编码';
COMMENT ON COLUMN T_DICT_DATA.PARENT_CODE 			        		IS '父节点编码';
COMMENT ON COLUMN T_DICT_DATA.TREE_SORT 			          		IS '树排序';
COMMENT ON COLUMN T_DICT_DATA.TREE_LEAF 			          		IS '是否叶子节点  true/false';
COMMENT ON COLUMN T_DICT_DATA.TREE_LEVEL 			          		IS '叶子深度';
COMMENT ON COLUMN T_DICT_DATA.DICT_LABEL 				        	IS '字典标志';
COMMENT ON COLUMN T_DICT_DATA.DICT_VALUE 			          		IS '字典值';
COMMENT ON COLUMN T_DICT_DATA.DICT_NAME 			          		IS '字典名';
COMMENT ON COLUMN T_DICT_DATA.DICT_TAG 			            		IS '字典标识';
COMMENT ON COLUMN T_DICT_DATA.IS_SYS 				            	IS '是否系统使用 true/false';
COMMENT ON COLUMN T_DICT_DATA.IS_DEFAULT 				        	IS '是否默认选中 true/false';
COMMENT ON COLUMN T_DICT_DATA.THE_DESC 				         	 	IS '描述';
COMMENT ON COLUMN T_DICT_DATA.STATUS 		                		IS '是否可用';
COMMENT ON COLUMN T_DICT_DATA.UPDATE_USER_ID 	          			IS '更新操作员';
COMMENT ON COLUMN T_DICT_DATA.CREATE_USER_ID 	          			IS '创建操作员';
COMMENT ON COLUMN T_DICT_DATA.EXPIRE_DATETIME 	        			IS '过期时间';
COMMENT ON COLUMN T_DICT_DATA.UPDATE_DATETIME 	        			IS '更新时间';
COMMENT ON COLUMN T_DICT_DATA.CREATE_DATETIME 	        			IS '创建时间';

CREATE TABLE T_DICT
(
	ID                        		VARCHAR(64) NOT NULL PRIMARY KEY,
	DICT_NAME                 		VARCHAR(128) NOT NULL,
	DICT_TYPE                 		VARCHAR(128) NOT NULL,
	THE_DESC                  		VARCHAR(1024),
	IS_SYS                    		VARCHAR(64) NOT NULL,
	STATUS                    		VARCHAR(64),
	UPDATE_USER_ID            		VARCHAR(64),
	CREATE_USER_ID            		VARCHAR(64),
	EXPIRE_DATETIME					TIMESTAMP WITHOUT TIME ZONE,
	UPDATE_DATETIME           		TIMESTAMP WITHOUT TIME ZONE,
	CREATE_DATETIME           		TIMESTAMP WITHOUT TIME ZONE
);

CREATE SEQUENCE SEQ_DICT_ID INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;

CREATE UNIQUE INDEX I_DICT_NAME ON T_DICT (DICT_NAME);

COMMENT ON TABLE  T_DICT 					                IS '字典类型表';
COMMENT ON COLUMN T_DICT.ID 				                IS '字典编码';
COMMENT ON COLUMN T_DICT.DICT_NAME 			          		IS '字典名称';
COMMENT ON COLUMN T_DICT.DICT_TYPE 			          		IS '字典类型';
COMMENT ON COLUMN T_DICT.IS_SYS 				            IS '是否系统使用 true/false';
COMMENT ON COLUMN T_DICT.THE_DESC 				          	IS '描述';
COMMENT ON COLUMN T_DICT.STATUS 		                	IS '是否可用';
COMMENT ON COLUMN T_DICT.UPDATE_USER_ID 	          		IS '更新操作员';
COMMENT ON COLUMN T_DICT.CREATE_USER_ID 	          		IS '创建操作员';
COMMENT ON COLUMN T_DICT.EXPIRE_DATETIME 	        		IS '过期时间';
COMMENT ON COLUMN T_DICT.UPDATE_DATETIME 	        		IS '更新时间';
COMMENT ON COLUMN T_DICT.CREATE_DATETIME 	        		IS '创建时间';


CREATE TABLE T_MCC_DEF
(
	ID                        		VARCHAR(64) NOT NULL PRIMARY KEY,
	MCC_CODE                  		VARCHAR(8) NOT NULL,
	OFFICIAL_NAME_EN                VARCHAR(1024) NOT NULL,
	OFFICIAL_NAME_CN               	VARCHAR(1024),
	IS_SYS                    		VARCHAR(64),
	STATUS                    		VARCHAR(64),
	UPDATE_USER_ID            		VARCHAR(64),
	CREATE_USER_ID            		VARCHAR(64),
	EXPIRE_DATETIME					TIMESTAMP WITHOUT TIME ZONE,
	UPDATE_DATETIME           		TIMESTAMP WITHOUT TIME ZONE,
	CREATE_DATETIME           		TIMESTAMP WITHOUT TIME ZONE
);

CREATE SEQUENCE SEQ_MCC_DEF_ID INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;

CREATE UNIQUE INDEX I_MCC_CODE ON T_MCC_DEF (MCC_CODE);

COMMENT ON TABLE  T_MCC_DEF 					            IS 'MCC 表';
COMMENT ON COLUMN T_MCC_DEF.ID 				                IS 'ID';
COMMENT ON COLUMN T_MCC_DEF.MCC_CODE 			            IS 'MCC CODE';
COMMENT ON COLUMN T_MCC_DEF.OFFICIAL_NAME_EN 			    IS '英文正式名字';
COMMENT ON COLUMN T_MCC_DEF.OFFICIAL_NAME_CN 				IS '英文中文名字';
COMMENT ON COLUMN T_MCC_DEF.IS_SYS 				            IS '是否系统使用 true/false';
COMMENT ON COLUMN T_MCC_DEF.STATUS 		                	IS '是否可用';
COMMENT ON COLUMN T_MCC_DEF.UPDATE_USER_ID 	          		IS '更新操作员';
COMMENT ON COLUMN T_MCC_DEF.CREATE_USER_ID 	          		IS '创建操作员';
COMMENT ON COLUMN T_MCC_DEF.EXPIRE_DATETIME 	        	IS '过期时间';
COMMENT ON COLUMN T_MCC_DEF.UPDATE_DATETIME 	        	IS '更新时间';
COMMENT ON COLUMN T_MCC_DEF.CREATE_DATETIME 	        	IS '创建时间';

CREATE TABLE T_COUNTRY_REGION
(
	ID                        		VARCHAR(64) NOT NULL PRIMARY KEY,
	COUNTRY_NUMBER            		VARCHAR(8) NOT NULL,
	OFFICIAL_NAME_EN          		VARCHAR(256),
	OFFICIAL_NAME_CN          		VARCHAR(256),
	LOCALE_NAME               		VARCHAR(256),
	REGION_CODE               		VARCHAR(6),
	IS_COUNTRY                		VARCHAR(64),
	IS_SYS                    		VARCHAR(64) NOT NULL,
	STATUS                    		VARCHAR(64),
	UPDATE_USER_ID            		VARCHAR(64),
	CREATE_USER_ID            		VARCHAR(64),
	UPDATE_DATETIME           		TIMESTAMP WITHOUT TIME ZONE,
	CREATE_DATETIME           		TIMESTAMP WITHOUT TIME ZONE
);

CREATE SEQUENCE SEQ_COUNTRY_REGION INCREMENT BY 1 MINVALUE 1 NO MAXVALUE START WITH 1;

CREATE INDEX I_REGION_CODE ON T_COUNTRY_REGION (REGION_CODE);
CREATE INDEX I_COUNTRY_NAME ON T_COUNTRY_REGION (COUNTRY_NUMBER,OFFICIAL_NAME_EN);
CREATE INDEX I_COUNTRY_REGION_NUMBER ON T_COUNTRY_REGION (COUNTRY_NUMBER);

COMMENT ON TABLE  T_COUNTRY_REGION 					        IS '国家地区表';
COMMENT ON COLUMN T_COUNTRY_REGION.ID 				        IS 'ID';
COMMENT ON COLUMN T_COUNTRY_REGION.COUNTRY_NUMBER 			IS '地区国家数字码';
COMMENT ON COLUMN T_COUNTRY_REGION.OFFICIAL_NAME_EN 		IS '英文正式名字';
COMMENT ON COLUMN T_COUNTRY_REGION.OFFICIAL_NAME_CN 		IS '英文中文名字';
COMMENT ON COLUMN T_COUNTRY_REGION.LOCALE_NAME 				IS '地区本地化名';
COMMENT ON COLUMN T_COUNTRY_REGION.REGION_CODE 				IS '地区CODE';
COMMENT ON COLUMN T_COUNTRY_REGION.IS_COUNTRY 				IS '是否是国家维度';
COMMENT ON COLUMN T_COUNTRY_REGION.IS_SYS 				    IS '是否系统使用 true/false';
COMMENT ON COLUMN T_COUNTRY_REGION.STATUS 		            IS '是否可用';
COMMENT ON COLUMN T_COUNTRY_REGION.UPDATE_USER_ID 	        IS '更新操作员';
COMMENT ON COLUMN T_COUNTRY_REGION.CREATE_USER_ID 	        IS '创建操作员';
COMMENT ON COLUMN T_COUNTRY_REGION.UPDATE_DATETIME 	        IS '更新时间';
COMMENT ON COLUMN T_COUNTRY_REGION.CREATE_DATETIME 	        IS '创建时间';