INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'0742','Veterinary Services','兽医服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'0743','Wine Producers','葡萄酒生产商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'0744','Champagne Producers','香槟生产商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'0763','Agricultural Cooperatives','农业合作社','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'0780','Landscaping and Horticultural Services','园林绿化和园艺服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'1520','General Contractors - Residential and Commercial','总承包商 - 住宅和商业','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'1711','Heating, Plumbing, and Air Conditioning Contractors','供暖，管道和空调承包商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'1731','Electrical Contractors','电气承包商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'1740','Masonry, Stonework, Tile-Setting, Plastering, and Insulation Contractors','砌体，石制品，瓷砖镶嵌，抹灰和绝缘承包商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'1750','Carpentry Contractors','木工承包商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'1761','Roofing, Siding, and Sheet Metal Work Contractors','屋面，壁板和钣金工作承包商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'1771','Concrete Work Contractors','具体工作承包商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'1799','Special Trade Contractors - Not Elsewhere Classified','特殊贸易承包商 - 不是其他地方分类','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'2741','Miscellaneous Publishing and Printing Services','杂项出版和印刷服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'2791','Typesetting, Plate Making, and Related Services','排版，制版和相关服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'2842','Specialty Cleaning, Polishing, and Sanitation Preparations','专业清洁，抛光和卫生准备','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4011','Railroads','铁路','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4111','Local and Suburban Commuter Passenger Transportation, including Ferries','本地和郊区通勤客运，包括渡轮','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4112','Passenger Railways','客运铁路','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4119','Ambulance Services','救护车服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4121','Taxicabs and Limousines','出租车和豪华轿车','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4131','Bus Lines','公交线路','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4214','Motor Freight Carriers and Trucking - Local and Long Distance, Moving and Storage Companies, and Local Delivery','汽车货运公司和货运公司 - 本地和长途，搬家和仓储公司以及本地交付','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4215','Courier Services - Air and Ground, and Freight Forwarders','快递服务 - 空运和陆运，以及货运代理','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4225','Public Warehousing and Storage - Farm Products, Refrigerated Goods, and Household Goods','公共仓储 - 农产品，冷藏货物和家庭用品','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4411','Steamship and Cruise Lines','轮船和游轮','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4457','Boat Rentals and Leasing','船租赁和租赁','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4468','Marinas, Marine Service, and Supplies','游艇码头，海事服务和用品','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4511','Airlines and Air Carriers','航空公司和航空公司','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4582','Airports, Flying Fields, and Airport Terminals','机场，飞行场和机场航站楼','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4722','Travel Agencies and Tour Operators','旅行社和旅游经营者','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4784','Tolls and Bridge Fees','通行费和桥费','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4789','Transportation Services - Not Elsewhere Classified','运输服务 - 不是其他地方分类','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4812','Telecommunication Equipment and Telephone Sales','电信设备和电话销售','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4814','Telecommunications Services, including Local and Long Distance Calls, Credit Card Calls, Calls','电信服务，包括本地和长途电话，信用卡呼叫，电话','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'thro','ugh use of Magnetic-Stripe-Reading Telephones, and Fax Services','使用磁条读取电话和传真服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4815','Monthly Summary Telephone Charges','每月摘要电话费','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4816','Comp Network/Information Services','Comp网络/信息服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4821','Telegraph Services','电报服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4829','Wire Transfers and Money Orders','电汇和汇票','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4899','Cable and Other Pay Television Services','有线和其他付费电视服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'4900','Utilities - Electric, Gas, Water, and Sanitary','公用事业 - 电力，燃气，水和卫生','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5013','Motor Vehicle Supplies and New Parts','汽车用品和新零件','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5021','Office and Commercial Furniture','办公室和商业家具','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5039','Construction Materials - Not Elsewhere Classified','建筑材料 - 不是其他地方分类','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5044','Office, Photographic, Photocopy, and Microfilm Equipment','办公室，摄影，影印和缩微胶卷设备','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5045','Computers, Computer Peripheral Equipment, and Software','计算机，计算机外围设备和软件','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5046','Commercial Equipment - Not Elsewhere Classified','商业设备 - 不是其他地方分类','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5047','Dental/Laboratory/Medical/ Ophthalmic Hospital Equipment and Supplies','牙科/实验室/医疗/眼科医院设备和用品','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5051','Metal Service Centers and Offices','金属服务中心和办公室','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5065','Electrical Parts and Equipment','电气零件和设备','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5072','Hardware Equipment and Supplies','硬件设备和用品','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5074','Plumbing and Heating Equipment and Supplies','管道和加热设备和用品','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5085','Industrial Supplies - Not Elsewhere Classified','工业用品 - 不是其他地方分类','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5094','Precious Stones and Metals, Watches, and Jewelry','宝石和金属，手表和珠宝','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5099','Durable Goods - Not Elsewhere Classified','耐用品 - 不是其他地方分类','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5111','Stationery, Office Supplies, Printing and Writing Paper','文具，办公用品，印刷和书写纸','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5122','Drugs, Drug Proprietors, and Druggists’ Sundries','毒品，毒品所有者和药剂师的杂物','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5131','Piece Goods, Notions, and Other Dry Goods','件商品，概念和其他干货','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5137','Men’s, Women’s, and Children’s Uniforms and Commercial Clothing','男士，女士，儿童制服和商业服装','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5139','Commercial Footwear','商业鞋','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5169','Chemicals and Allied Products - Not Elsewhere Classified','化学品和相关产品 - 不在其他地方','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5172','Petroleum and Petroleum Products','石油和石油产品','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5192','Books, Periodicals, and Newspapers','书籍，期刊和报纸','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5193','Florists’ Supplies, Nursery Stock, and Flowers','花店用品，苗圃和鲜花','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5198','Paints, Varnishes, and Supplies','油漆，清漆和用品','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5199','Non-Durable Goods - Not Elsewhere Classified','非耐用品 - 不在其他地方分类','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5200','Home Supply Warehouse Stores','家庭供应仓库商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5211','Lumber and Building Materials Stores','木材和建材商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5231','Glass, Paint, and Wallpaper Stores','玻璃，油漆和壁纸商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5251','Hardware Stores','五金店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5261','Lawn and Garden Supply Stores, including Nurseries','草坪和花园供应商店，包括苗圃','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5271','Mobile Home Dealers','移动房屋经销商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5300','Wholesale Clubs','批发俱乐部','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5309','Duty Free Stores','免税商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5310','Discount Stores','折扣店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5311','Department Stores','百货商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5331','Variety Stores','百货商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5399','Miscellaneous General Merchandise','杂项杂货','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5411','Grocery Stores and Supermarkets','杂货店和超市','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5422','Freezer and Locker Meat Provisioners','冰柜和储物柜肉供应商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5441','Candy, Nut, and Confectionery Stores','糖果，坚果和糖果店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5451','Dairy Products Stores','乳制品商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5462','Bakeries','面包店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5499','Miscellaneous Food Stores - Convenience Stores and Specialty Markets','杂项食品店 - 便利店和专业市场','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5511','Car and Truck Dealers (New and Used) Sales, Service, Repairs, Parts, and Leasing','汽车和卡车经销商（新旧）销售，服务，维修，零件和租赁','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5521','Car and Truck Dealers (Used Only) Sales, Service, Repairs, Parts, and Leasing','汽车和卡车经销商（仅限使用）销售，服务，维修，零件和租赁','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5531','Auto and Home Supply Stores','汽车和家庭用品商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5532','Automotive Tire Stores','汽车轮胎商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5533','Auto Parts and Accessories Stores','汽车零配件商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5541','Service Stations (with or without Ancillary Services)','服务站（有或没有辅助服务）','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5542','Automated Fuel Dispensers','自动燃油分配器','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5551','Boat Dealers','船经销商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5561','Camper, Recreational, and Utility Trailer Dealers','Camper，Recreational和Utility Trailer经销商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5571','Motorcycle Shops and Dealers','摩托车商店和经销商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5592','Motor Home Dealers','汽车之家经销商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5598','Snowmobile Dealers','雪地车经销商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5599','Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers - Not Elsewhere Classified','杂项汽车，飞机和农场设备经销商 - 其他地方没有分类','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5611','Men’s and Boys Clothing and Accessory Stores','男士和男士服装及配饰店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5621','Women’s Ready To Wear Stores','妇女准备好商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5631','Women’s Accessory and Specialty Stores','妇女的配件和专卖店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5641','Children’s and Infants’ Wear Stores','儿童和婴儿服装店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5651','Family Clothing Stores','家庭服装店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5655','Sports and Riding Apparel Stores','运动和骑马服装店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5661','Shoe Stores','鞋店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5681','Furriers and Fur Shops','毛皮商店和毛皮商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5691','Men’s and Women’s Clothing Stores','男士和女士服装店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5697','Tailors, Seamstresses, Mending, and Alterations','裁缝，裁缝，修补和改造','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5698','Wig and Toupee Stores','假发和假发商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5699','Miscellaneous Apparel and Accessory Stores','杂项服装和配饰商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5712','Furniture, Home Furnishings and Equipment Stores, and Manufacturers, except Appliances','家具，家居用品和设备商店，以及制造商，电器除外','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5713','Floor Covering Stores','地板覆盖商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5714','Drapery, Window Covering, and Upholstery Stores','窗帘，窗帘和室内装潢商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5715','Alcoholic Beverage Wholesalers','酒精饮料批发商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5718','Fireplaces, Fireplace Screens, and Accessories Stores','壁炉，壁炉屏幕和配件商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5719','Miscellaneous Home Furnishings Specialty Stores','杂项家居专卖店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5722','Household Appliance Stores','家用电器商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5732','Electronics Stores','电子产品商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5733','Music Stores - Musical Instruments, Pianos, and Sheet Music','音乐商店 - 乐器，钢琴和乐谱','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5734','Computer Software Stores','计算机软件商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5735','Record Strores','记录Strores','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5811','Caterers','餐饮业','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5812','Eating Places and Restaurants','吃饭的地方和餐馆','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5813','Drinking Places (Alcoholic Beverages) - Bars, Taverns, Nightclubs, Cocktail Lounges, and Discotheques','饮酒场所（酒精饮料） - 酒吧，酒馆，夜总会，鸡尾酒休息室和迪斯科舞厅','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5814','Fast Food Restaurants','快餐店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5815','Digitial Goods - Media: Books, Movies, Music','数字商品 - 媒体：书籍，电影，音乐','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5816','Digital Goods - Games','数字商品 - 游戏','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5817','Digital Goods - Apps (Excludes Games)','数字商品 - 应用程序（不包括游戏）','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5818','Large Digital Goods Merchants','大型数字商品商人','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5912','Drug Stores and Pharmacies','药店和药店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5921','Package Stores - Beer, Wine, and Liquor','包装店 - 啤酒，葡萄酒和白酒','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5931','Used Merchandise and Secondhand Stores','二手商品和二手商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5932','Antique Shops - Sales, Repairs, and Restoration Services','古董店 - 销售，维修和修复服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5933','Pawn Shops','当铺','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5935','Wrecking and Salvage Yards','破坏和打捞码','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5937','Antique Reproduction Stores','古董再生商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5940','Bicycle Shops - Sales and Service','自行车商店 - 销售和服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5941','Sporting Goods Stores','体育用品商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5942','Book Stores','书店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5943','Stationery, Office, and School Supply Stores','文具，办公室和学校用品店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5944','Jewelry, Watch, Clock, and Silverware Stores','珠宝，手表，时钟和银器商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5945','Hobby, Toy, and Game Stores','爱好，玩具和游戏商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5946','Camera and Photographic Supply Stores','相机和摄影用品商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5947','Gift, Card, Novelty, and Souvenir Stores','礼品，卡片，新奇和纪念品商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5948','Luggage and Leather Goods Stores','行李箱和皮具商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5949','Sewing, Needlework, Fabric, and Piece Goods Stores','缝纫，针线，布料和件商品','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5950','Glassware and Crystal Stores','玻璃器皿和水晶店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5960','Direct Marketing - Insurance Services','直接营销 - 保险服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5962','Telemarketing - Travel-Related Arrangement Services','电话营销 - 与旅行相关的安排服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5963','Door-to-Door Sales','门到门销售','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5964','Direct Marketing Catalog Merchants','直销商品目录','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5965','Direct Marketing - Combination Catalog and Retail Merchants','直接营销 - 组合目录和零售商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5966','Direct Marketing - Outbound Telemarketing Merchants','直接营销 - 出境电话营销商家','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5967','Direct Marketing - Inbound Telemarketing Merchants','直接营销 - 入境电话营销商家','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5968','Direct Marketing - Continuity/Subscription Merchants','直接营销 - 连续性/订阅商家','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5969','Direct Marketing/Direct Marketers - Not Elsewhere Classified','直接营销/直接营销人员 - 不是其他地方分类','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5970','Artist Supply and Craft Stores','艺术家供应和工艺品商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5971','Art Dealers and Galleries','艺术品经销商和画廊','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5972','Stamp and Coin Stores','邮票和硬币商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5973','Religious Goods Stores','宗教用品商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5975','Hearing Aids Sales, Service, and Supplies','助听器销售，服务和用品','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5976','Orthopedic Goods and Prosthetic Devices','骨科用品和假肢装置','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5977','Cosmetic Stores','化妆品店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5978','Typewriter Stores - Sales, Service, and Rentals','打字机商店 - 销售，服务和租赁','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5983','Fuel Dealers - Fuel Oil, Wood, Coal, and Liquefied Petroleum','燃料经销商 - 燃料油，木材，煤和液化石油','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5992','Florists','花店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5993','Cigar Stores and Stands','雪茄商店和摊位','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5994','News Dealers and Newsstands','新闻经销商和报摊','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5995','Pet Shops, Pet Food and Supplies','宠物店，宠物食品和用品','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5996','Swimming Pools - Sales, Supplies, and Services','游泳池 - 销售，供应和服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5997','Electric Razor Stores - Sales and Service','电动剃须刀店 - 销售和服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5998','Tent and Awning Stores','帐篷和遮阳篷商店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'5999','Miscellaneous and Specialty Retail','杂项和专业零售','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'6010','Financial Institutions - Manual Cash Disbursements','金融机构 - 手工现金支付','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'6011','Financial Institutions - Automated Cash Disbursements','金融机构 - 自动现金支付','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'6012','Financial Institutions - Merchandise and Services','金融机构 - 商品和服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'6051','Non Financial Institutions - Foreign Currency, Money Orders, (not Wire Transfer), Scrip, and Travelers Cheques','非金融机构 - 外币，汇票，（不是电汇），Scrip和旅行支票','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'6211','Securities - Brokers and Dealers','证券 - 经纪人和经销商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'6300','Insurance Sales, Underwriting, and Premiums','保险销售，承销和保费','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'6513','Real Estate (e.g., rent)','房地产（例如租金）','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7011','Lodging Hotels, Motels, and Resorts','住宿酒店，汽车旅馆和度假村','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7012','Timeshares','分时度假','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7032','Sporting and Recreational Camps','运动和休闲营地','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7033','Trailer Parks and Campgrounds','拖车公园和露营地','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7210','Laundry, Cleaning and Garment Services','洗衣，清洁和服装服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7211','Laundry Services - Family and Commercial','洗衣服务 - 家庭和商业','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7216','Dry Cleaners','干洗店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7217','Carpet and Upholstery Cleaning','地毯和室内装潢清洁','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7221','Photographic Studios','摄影工作室','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7230','Beauty and Barber Shops','美容和理发店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7251','Shoe Repair Shops, Shoe Shine Parlors, and Hat Cleaning Shops','鞋修理店，擦鞋店和帽子清洁店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7261','Funeral Services and Crematories','殡仪服务和火葬场','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7273','Dating and Escort Services','约会和陪同服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7276','Tax Preparation Services','税务准备服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7277','Counseling Services - Debt, Marriage, and Personal','咨询服务 - 债务，婚姻和个人','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7278','Buying and Shopping Services and Clubs','购买和购物服务和俱乐部','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7296','Clothing Rental - Costumes, Uniforms, and Formal Wear','服装出租 - 服装，制服和正式服装','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7297','Massage Parlors','按摩院','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7298','Health and Beauty Spas','健康与美容水疗','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7299','Miscellaneous Personal Services - Not Elsewhere Classified','杂项个人服务 - 不在其他地方分类','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7311','Advertising Services','广告服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7321','Consumer Credit Reporting Agencies','消费者信用报告机构','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7322','Debt Collection Agencies','债务催收机构','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7333','Commercial Photography, Art, and Graphics','商业摄影，艺术和图形','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7338','Quick Copy, Reproduction, and Blueprinting Services','快速复制，复制和蓝图服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7339','Stenographic and Secretarial Support Services','速记和秘书支持服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7342','Exterminating and Disinfecting Services','消灭和消毒服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7349','Cleaning, Maintenance, and Janitorial Services','清洁，维护和清洁服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7361','Employment Agencies and Temporary Help Services','就业机构和临时帮助服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7372','Computer Programming, Data Processing, and Integrated Systems Design Services','计算机编程，数据处理和集成系统设计服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7375','Information Retrieval Services','信息检索服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7379','Computer Maintenance and Repair Services - Not Elsewhere Classified','计算机维护和维修服务 - 不在其他地方','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7392','Management, Consulting, and Public Relations Services','管理，咨询和公共关系服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7393','Detective Agencies, Protective Agencies, and Security Services, including Armored Cars and Guard Dogs','侦探机构，保护机构和安全服务，包括装甲车和护卫犬','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7394','Equipment, Tool, Furniture, and Appliance Rental and Leasing','设备，工具，家具和设备租赁和租赁','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7395','Photo Finishing Laboratories and Photo Developing','照片整理实验室和照片开发','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7399','Business Services -Not Elsewhere Classified','商业服务 - 其他地方分类','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7512','Automobile Rental Agency','汽车租赁公司','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7513','Truck and Utility Trailer Rentals','卡车和公用拖车租赁','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7519','Motor Home and Recreational Vehicle Rentals','汽车之家和休闲车租赁','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7523','Parking Lots and Garages','停车场和车库','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7531','Automotive Body Repair Shops','汽车车身修理厂','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7534','Tire Re-Treading and Repair Shops','轮胎重新踩踏和修理店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7535','Automotive Paint Shops','汽车油漆店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7538','Automotive Service Shops (Non-Dealer)','汽车服务店（非经销商）','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7542','Car Washes','洗车','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7549','Towing Services','拖车服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7622','Electronics Repair Shops','电子维修店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7623','Air Conditioning and Refrigeration Repair Shops','空调和制冷维修店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7629','Electrical and Small Appliance Repairs','电器和小家电维修','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7631','Watch, Clock, and Jewelry Repair Shops','手表，钟表和珠宝维修店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7641','Furniture - Re-Upholstery, Repair, and Refinishing','家具 - 重新装饰，修理和修补','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7692','Welding Services','焊接服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7699','Miscellaneous Repair Shops and Related Services','杂项维修店及相关服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7829','Motion Picture and Video Tape Production and Distribution','电影和录像带的制作和发行','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7832','Motion Picture Theaters','电影院','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7841','Video Tape Rental Stores','录像带租赁店','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7911','Dance Halls, Studios, and Schools','舞厅，工作室和学校','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7922','Theatrical Producers (except Motion Pictures) and Ticket Agencies','戏剧制作人（电影除外）和票务代理商','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7929','Bands, Orchestras, and Miscellaneous Entertainers - Not Elsewhere Classified','乐队，管弦乐队和杂项演艺人员 - 不是其他地方分类','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7932','Billiard and Pool Establishments','台球和游泳池设施','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7933','Bowling Alleys','保龄球馆','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7941','Commercial Sports, Professional Sports Clubs, Athletic Fields, and Sports Promoters','商业体育，职业体育俱乐部，运动场和体育推广者','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7991','Tourist Attractions and Exhibits','旅游景点和展览','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7992','Public Golf Courses','公共高尔夫球场','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7993','Video Amusement Game Supplies','视频游戏用品','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7994','Video Game Arcades and Establishments','视频游戏商场和企业','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7995','Betting, including Lottery Tickets, Casino Gaming Chips, Off-Track Betting, and Wagers at Race Tracks','投注，包括彩票，赌场游戏筹码，场外投注和赛道上的投手','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7996','Amusement Parks, Circuses, Carnivals, and Fortune Tellers','游乐园，马戏团，狂欢节和算命先生','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7997','Membership Clubs (Sports, Recreation, Athletic), Country Clubs, and Private Golf Courses','会员俱乐部（体育，娱乐，体育），乡村俱乐部和私人高尔夫球场','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7998','Aquariums, Seaquariums, and Dolphinariums','水族馆，海洋水族馆和海豚馆','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'7999','Recreation Services - Not Elsewhere Classified','康乐服务 - 不是其他地方分类','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8011','Doctors and Physicians - Not Elsewhere Classified','医生和医生 - 不是其他地方分类','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8021','Dentists and Orthodontists','牙医和牙齿矫正医生','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8031','Osteopaths','整骨','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8041','Chiropractors','脊医','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8042','Optometrists and Ophthalmologists','验光师和眼科医生','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8043','Opticians, Optical Goods, and Eyeglasses','眼镜商，眼镜商品和眼镜','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8049','Podiatrists and Chiropodists','足病医生和手足病医生','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8050','Nursing and Personal Care Facilities','护理和个人护理设施','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8062','Hospitals','医院','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8071','Medical and Dental Laboratories','医学和牙科实验室','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8099','Medical Services and Health Practitioners - Not Elsewhere Classified','医疗服务和卫生从业人员 - 不是其他地方','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8111','Legal Services and Attorneys','法律服务和律师','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8211','Elementary and Secondary Schools','中小学','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8220','Colleges, Universities, Professional Schools, and Junior Colleges','学院，大学，专业学校和初级学院','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8241','Correspondence Schools','函授学校','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8244','Business and Secretarial Schools','商业和秘书学校','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8249','Trade and Vocational Schools','贸易和职业学校','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8299','Schools and Educational Services - Not Elsewhere Classified','学校和教育服务 - 不在其他地方','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8351','Child Care Services','托儿服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8398','Charitable and Social Service Organizations','慈善和社会服务组织','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8641','Civic, Social, and Fraternal Associations','公民，社会和兄弟协会','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8651','Political Organizations','政治组织','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8661','Religious Organizations','宗教组织','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8675','Automobile Associations','汽车协会','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8699','Membership Organizations - Not Elsewhere Classified','会员组织 - 不是其他地方分类','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8734','Testing Laboratories (Non-Medical)','检测实验室（非医疗）','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8911','Architectural, Engineering, and Surveying Services','建筑，工程和测量服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8931','Accounting, Auditing, and Bookkeeping Services','会计，审计和簿记服务','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'8999','Professional Services - Not Elsewhere Classified','专业服务 - 不是其他地方分类','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'9211','Court Costs, including Alimony and Child Support','法庭费用，包括赡养费和子女抚养费','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'9222','Fines','罚款','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'9223','Bail and Bond Payments','保释金和债券支付','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'9311','Tax Payments','纳税','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'9399','Government Services - Not Elsewhere Classified','政府服务 - 不是其他地方','true');
INSERT INTO T_MCC_DEF(ID, MCC_CODE, OFFICIAL_NAME_EN, OFFICIAL_NAME_CN, IS_SYS) values ( nextval('SEQ_MCC_DEF_ID'),'9402','Postal Services Government Only','邮政服务政府','true');
